### ISSUE TITLE
possible python 2 to 3 bug leads to wrong type for taskrange

### ISSUE THREAD

**Issue by xzackli** [simonsobs/pspy#14]
I think the following line is probably not intentional, but I want to make sure.

https://github.com/simonsobs/pspy/blob/8ef1abfb517955908175e4611201979d1f2c971f/pspy/so_mpi.py#L112

This line causes taskrange to generate a list of floating point numbers for the task ids, because in python 3 the `/` always generates a float. It should probably be `//`.

**Comment by xgarrido** [comment]
You're right (see #16)
